## Урок 1. Алгоритм линейной регрессии. Градиентный спуск

In [34]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2]])
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  5,  3,  0,  5, 10,  1,  2]])

In [36]:
y = [45, 55, 50, 55, 60, 35, 75, 80, 50, 60]

In [37]:
X.T

array([[ 1,  1],
       [ 1,  1],
       [ 1,  2],
       [ 1,  5],
       [ 1,  3],
       [ 1,  0],
       [ 1,  5],
       [ 1, 10],
       [ 1,  1],
       [ 1,  2]])

In [38]:
W = np.linalg.inv(np.dot(X, X.T)) @ X @ y
W

array([45.0625,  3.8125])

In [39]:
W

array([45.0625,  3.8125])

In [40]:
def calc_mae(y, y_pred):
    err = np.mean(np.abs(y - y_pred))
    return err

def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2) # <=> 1/n * np.sum((y_pred - y)**2)
    return err

1. Подберем скорость обучения (alpha) и количество итераций

Была идея подобрать альфа обратно пропорционально количеству итераций, но в результате, простой подбор гораздо лучше показывает результат

In [43]:
W = np.array([1, 0.5])
W.shape[0]

2

In [44]:
W

array([1. , 0.5])

In [45]:
y

[45, 55, 50, 55, 60, 35, 75, 80, 50, 60]

In [46]:
W.shape[0]

2

In [47]:
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  5,  3,  0,  5, 10,  1,  2]])

In [48]:
n = X.shape[1]
alpha = 5e-2  #скорость обучения 0.05
W = np.array([1, 0.5])
print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

for i in range(1, 100):
    y_pred = np.dot(W, X) #умножаем к-ты на весь массив - единички на 
    err = calc_mse(y, y_pred)
    for k in range(W.shape[0]): # это и есть веса 1 - intercept  и 2 
        W[k] -= alpha * (1/n * 2 * np.sum(X[k] * (y_pred - y)))
    if i % 10 == 0: #печатаем каждую десятую итерацию 
        print(f'Iteration #{i}: W_new = {W}, MSE = {round(err,2)}')
        print ('')

Number of objects = 10        
Learning rate = 0.05        
Initial weights = [1.  0.5] 

Iteration #10: W_new = [18.55865432  7.9437319 ], MSE = 417.54

Iteration #20: W_new = [28.51033319  6.77368864], MSE = 185.56

Iteration #30: W_new = [34.6873853   5.69146143], MSE = 99.62

Iteration #40: W_new = [38.55696644  4.99203458], MSE = 65.85

Iteration #50: W_new = [40.98318343  4.55221259], MSE = 52.57

Iteration #60: W_new = [42.50454279  4.27634559], MSE = 47.35

Iteration #70: W_new = [43.4585188   4.10335723], MSE = 45.3

Iteration #80: W_new = [44.0567147   3.99488365], MSE = 44.49

Iteration #90: W_new = [44.43181676  3.92686468], MSE = 44.17



*2. В этом коде мы избавляемся от итераций по весам

In [49]:
n = X.shape[1]
alpha = 5e-2
W = np.array([1, 0.5])
print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

#исправить ошибку 
for i in range(100):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    W -= alpha * (1/n * 2 * X.dot (y_pred - y))
    if i % 10 == 0:
        print(f'Iteration #{i}: W_new = {W}, MSE = {round(err,2)}')

Number of objects = 10        
Learning rate = 0.05        
Initial weights = [1.  0.5] 

Iteration #0: W_new = [ 6.4  19.35], MSE = 3047.75
Iteration #10: W_new = [19.96966932  8.87179137], MSE = 379.6
Iteration #20: W_new = [29.27719328  6.70531799], MSE = 172.93
Iteration #30: W_new = [35.16120834  5.60976141], MSE = 94.66
Iteration #40: W_new = [38.85365942  4.93848587], MSE = 63.9
Iteration #50: W_new = [41.16920131  4.51849616], MSE = 51.81
Iteration #60: W_new = [42.62118483  4.25519525], MSE = 47.05
Iteration #70: W_new = [43.53165976  4.0900943 ], MSE = 45.18
Iteration #80: W_new = [44.10257814  3.98656703], MSE = 44.45
Iteration #90: W_new = [44.46057568  3.9216497 ], MSE = 44.16
